package com.maif.taskmanagerplus_api_rest_assured.model;

import lombok.Getter;
import lombok.Setter;

/**
 * TaskDTO class represents a Data Transfer Object for tasks.
 * This class contains properties for the task's title, description, due date, and completion status.
 * The getters and setters for these properties are automatically generated by Lombok.
 * 
 * Author: Maicon Fang
 * Date: 2024-06-19
 */
@Setter
@Getter
public class TaskDTO {
    private Integer id;
	private String title;
    private String description;
    private String dueDate;
    private Boolean completed;

    
    /**
     * Static method to create a TaskDTO with optional custom values.
     * If any parameter is null, a default value will be used.
     *
     * @param title       The title of the task (optional).
     * @param description The description of the task (optional).
     * @param dueDate     The due date of the task in ISO format (optional).
     * @param completed   Whether the task is completed (optional).
     * @return A TaskDTO object with the provided or default values.
     */
    public static TaskDTO createTask(String title, String description, String dueDate, Boolean completed) {
        TaskDTO taskDTO = new TaskDTO();
        taskDTO.setTitle(title != null ? title : "Default Task Title");
        taskDTO.setDescription(description != null ? description : "Default Task Description");
        taskDTO.setDueDate(dueDate != null ? dueDate : "2024-06-30T00:00:00Z");
        taskDTO.setCompleted(completed != null ? completed : false);
        return taskDTO;
    }
    
    public static TaskDTO createTask(Integer id, String title, String description, String dueDate, Boolean completed) {
        TaskDTO taskDTO = new TaskDTO();
        taskDTO.setId(id);
        taskDTO.setTitle(title != null ? title : "Default Task Title");
        taskDTO.setDescription(description != null ? description : "Default Task Description");
        taskDTO.setDueDate(dueDate != null ? dueDate : "2024-06-30T00:00:00Z");
        taskDTO.setCompleted(completed != null ? completed : false);
        return taskDTO;
    }
    
    // Getters and Setters are automatically generated by Lombok
}
