package com.maif.taskmanagerplus_api_rest_assured.model;

import lombok.Getter;
import lombok.Setter;

/**
 * TaskDTO class represents a Data Transfer Object for tasks.
 * This class contains properties for the task's title, description, due date, and completion status.
 * The getters and setters for these properties are automatically generated by Lombok.
 * 
 * Author: Maicon Fang
 * Date: 2024-06-19
 */
@Setter
@Getter
public class TaskDTO {
    private String title;
    private String description;
    private String dueDate;
    private Boolean completed;

    // Getters and Setters are automatically generated by Lombok
}
